//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioDinet.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbModelEntities : DbContext
    {
        public DbModelEntities()
            : base("name=DbModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MOV_INVENTARIO> MOV_INVENTARIO { get; set; }
    
        public virtual ObjectResult<SP_CONSULTA_INVENTARIO_Result> SP_CONSULTA_INVENTARIO(string codCia, string companiaVenta3, string almacenVenta, string tipoMovimiento, string tipoDocumento, string nroDocumento, string codItem2, string proveedor, string almacenDestino, Nullable<int> cantidad, string docRef1, string docRef2, string docRef3, string docRef4, string docRef5, Nullable<System.DateTime> fechaTransaccion)
        {
            var codCiaParameter = codCia != null ?
                new ObjectParameter("codCia", codCia) :
                new ObjectParameter("codCia", typeof(string));
    
            var companiaVenta3Parameter = companiaVenta3 != null ?
                new ObjectParameter("companiaVenta3", companiaVenta3) :
                new ObjectParameter("companiaVenta3", typeof(string));
    
            var almacenVentaParameter = almacenVenta != null ?
                new ObjectParameter("almacenVenta", almacenVenta) :
                new ObjectParameter("almacenVenta", typeof(string));
    
            var tipoMovimientoParameter = tipoMovimiento != null ?
                new ObjectParameter("tipoMovimiento", tipoMovimiento) :
                new ObjectParameter("tipoMovimiento", typeof(string));
    
            var tipoDocumentoParameter = tipoDocumento != null ?
                new ObjectParameter("tipoDocumento", tipoDocumento) :
                new ObjectParameter("tipoDocumento", typeof(string));
    
            var nroDocumentoParameter = nroDocumento != null ?
                new ObjectParameter("nroDocumento", nroDocumento) :
                new ObjectParameter("nroDocumento", typeof(string));
    
            var codItem2Parameter = codItem2 != null ?
                new ObjectParameter("codItem2", codItem2) :
                new ObjectParameter("codItem2", typeof(string));
    
            var proveedorParameter = proveedor != null ?
                new ObjectParameter("proveedor", proveedor) :
                new ObjectParameter("proveedor", typeof(string));
    
            var almacenDestinoParameter = almacenDestino != null ?
                new ObjectParameter("almacenDestino", almacenDestino) :
                new ObjectParameter("almacenDestino", typeof(string));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            var docRef1Parameter = docRef1 != null ?
                new ObjectParameter("docRef1", docRef1) :
                new ObjectParameter("docRef1", typeof(string));
    
            var docRef2Parameter = docRef2 != null ?
                new ObjectParameter("docRef2", docRef2) :
                new ObjectParameter("docRef2", typeof(string));
    
            var docRef3Parameter = docRef3 != null ?
                new ObjectParameter("docRef3", docRef3) :
                new ObjectParameter("docRef3", typeof(string));
    
            var docRef4Parameter = docRef4 != null ?
                new ObjectParameter("docRef4", docRef4) :
                new ObjectParameter("docRef4", typeof(string));
    
            var docRef5Parameter = docRef5 != null ?
                new ObjectParameter("docRef5", docRef5) :
                new ObjectParameter("docRef5", typeof(string));
    
            var fechaTransaccionParameter = fechaTransaccion.HasValue ?
                new ObjectParameter("fechaTransaccion", fechaTransaccion) :
                new ObjectParameter("fechaTransaccion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CONSULTA_INVENTARIO_Result>("SP_CONSULTA_INVENTARIO", codCiaParameter, companiaVenta3Parameter, almacenVentaParameter, tipoMovimientoParameter, tipoDocumentoParameter, nroDocumentoParameter, codItem2Parameter, proveedorParameter, almacenDestinoParameter, cantidadParameter, docRef1Parameter, docRef2Parameter, docRef3Parameter, docRef4Parameter, docRef5Parameter, fechaTransaccionParameter);
        }
    
        public virtual int SP_ACTUALIZACION_INVENTARIO(string codCia, string companiaVenta3, string almacenVenta, string tipoMovimiento, string tipoDocumento, string nroDocumento, string codItem2, string proveedor, string almacenDestino, Nullable<int> cantidad, string docRef1, string docRef2, string docRef3, string docRef4, string docRef5, Nullable<System.DateTime> fechaTransaccion)
        {
            var codCiaParameter = codCia != null ?
                new ObjectParameter("codCia", codCia) :
                new ObjectParameter("codCia", typeof(string));
    
            var companiaVenta3Parameter = companiaVenta3 != null ?
                new ObjectParameter("companiaVenta3", companiaVenta3) :
                new ObjectParameter("companiaVenta3", typeof(string));
    
            var almacenVentaParameter = almacenVenta != null ?
                new ObjectParameter("almacenVenta", almacenVenta) :
                new ObjectParameter("almacenVenta", typeof(string));
    
            var tipoMovimientoParameter = tipoMovimiento != null ?
                new ObjectParameter("tipoMovimiento", tipoMovimiento) :
                new ObjectParameter("tipoMovimiento", typeof(string));
    
            var tipoDocumentoParameter = tipoDocumento != null ?
                new ObjectParameter("tipoDocumento", tipoDocumento) :
                new ObjectParameter("tipoDocumento", typeof(string));
    
            var nroDocumentoParameter = nroDocumento != null ?
                new ObjectParameter("nroDocumento", nroDocumento) :
                new ObjectParameter("nroDocumento", typeof(string));
    
            var codItem2Parameter = codItem2 != null ?
                new ObjectParameter("codItem2", codItem2) :
                new ObjectParameter("codItem2", typeof(string));
    
            var proveedorParameter = proveedor != null ?
                new ObjectParameter("proveedor", proveedor) :
                new ObjectParameter("proveedor", typeof(string));
    
            var almacenDestinoParameter = almacenDestino != null ?
                new ObjectParameter("almacenDestino", almacenDestino) :
                new ObjectParameter("almacenDestino", typeof(string));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            var docRef1Parameter = docRef1 != null ?
                new ObjectParameter("docRef1", docRef1) :
                new ObjectParameter("docRef1", typeof(string));
    
            var docRef2Parameter = docRef2 != null ?
                new ObjectParameter("docRef2", docRef2) :
                new ObjectParameter("docRef2", typeof(string));
    
            var docRef3Parameter = docRef3 != null ?
                new ObjectParameter("docRef3", docRef3) :
                new ObjectParameter("docRef3", typeof(string));
    
            var docRef4Parameter = docRef4 != null ?
                new ObjectParameter("docRef4", docRef4) :
                new ObjectParameter("docRef4", typeof(string));
    
            var docRef5Parameter = docRef5 != null ?
                new ObjectParameter("docRef5", docRef5) :
                new ObjectParameter("docRef5", typeof(string));
    
            var fechaTransaccionParameter = fechaTransaccion.HasValue ?
                new ObjectParameter("fechaTransaccion", fechaTransaccion) :
                new ObjectParameter("fechaTransaccion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ACTUALIZACION_INVENTARIO", codCiaParameter, companiaVenta3Parameter, almacenVentaParameter, tipoMovimientoParameter, tipoDocumentoParameter, nroDocumentoParameter, codItem2Parameter, proveedorParameter, almacenDestinoParameter, cantidadParameter, docRef1Parameter, docRef2Parameter, docRef3Parameter, docRef4Parameter, docRef5Parameter, fechaTransaccionParameter);
        }
    
        public virtual int SP_ELIMINACION_INVENTARIO(string codCia, string companiaVenta3, string almacenVenta, string tipoMovimiento, string tipoDocumento, string nroDocumento, string codItem2)
        {
            var codCiaParameter = codCia != null ?
                new ObjectParameter("codCia", codCia) :
                new ObjectParameter("codCia", typeof(string));
    
            var companiaVenta3Parameter = companiaVenta3 != null ?
                new ObjectParameter("companiaVenta3", companiaVenta3) :
                new ObjectParameter("companiaVenta3", typeof(string));
    
            var almacenVentaParameter = almacenVenta != null ?
                new ObjectParameter("almacenVenta", almacenVenta) :
                new ObjectParameter("almacenVenta", typeof(string));
    
            var tipoMovimientoParameter = tipoMovimiento != null ?
                new ObjectParameter("tipoMovimiento", tipoMovimiento) :
                new ObjectParameter("tipoMovimiento", typeof(string));
    
            var tipoDocumentoParameter = tipoDocumento != null ?
                new ObjectParameter("tipoDocumento", tipoDocumento) :
                new ObjectParameter("tipoDocumento", typeof(string));
    
            var nroDocumentoParameter = nroDocumento != null ?
                new ObjectParameter("nroDocumento", nroDocumento) :
                new ObjectParameter("nroDocumento", typeof(string));
    
            var codItem2Parameter = codItem2 != null ?
                new ObjectParameter("codItem2", codItem2) :
                new ObjectParameter("codItem2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINACION_INVENTARIO", codCiaParameter, companiaVenta3Parameter, almacenVentaParameter, tipoMovimientoParameter, tipoDocumentoParameter, nroDocumentoParameter, codItem2Parameter);
        }
    
        public virtual int SP_INSERCION_INVENTARIO(string codCia, string companiaVenta3, string almacenVenta, string tipoMovimiento, string tipoDocumento, string nroDocumento, string codItem2, string proveedor, string almacenDestino, Nullable<int> cantidad, string docRef1, string docRef2, string docRef3, string docRef4, string docRef5, Nullable<System.DateTime> fechaTransaccion)
        {
            var codCiaParameter = codCia != null ?
                new ObjectParameter("codCia", codCia) :
                new ObjectParameter("codCia", typeof(string));
    
            var companiaVenta3Parameter = companiaVenta3 != null ?
                new ObjectParameter("companiaVenta3", companiaVenta3) :
                new ObjectParameter("companiaVenta3", typeof(string));
    
            var almacenVentaParameter = almacenVenta != null ?
                new ObjectParameter("almacenVenta", almacenVenta) :
                new ObjectParameter("almacenVenta", typeof(string));
    
            var tipoMovimientoParameter = tipoMovimiento != null ?
                new ObjectParameter("tipoMovimiento", tipoMovimiento) :
                new ObjectParameter("tipoMovimiento", typeof(string));
    
            var tipoDocumentoParameter = tipoDocumento != null ?
                new ObjectParameter("tipoDocumento", tipoDocumento) :
                new ObjectParameter("tipoDocumento", typeof(string));
    
            var nroDocumentoParameter = nroDocumento != null ?
                new ObjectParameter("nroDocumento", nroDocumento) :
                new ObjectParameter("nroDocumento", typeof(string));
    
            var codItem2Parameter = codItem2 != null ?
                new ObjectParameter("codItem2", codItem2) :
                new ObjectParameter("codItem2", typeof(string));
    
            var proveedorParameter = proveedor != null ?
                new ObjectParameter("proveedor", proveedor) :
                new ObjectParameter("proveedor", typeof(string));
    
            var almacenDestinoParameter = almacenDestino != null ?
                new ObjectParameter("almacenDestino", almacenDestino) :
                new ObjectParameter("almacenDestino", typeof(string));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            var docRef1Parameter = docRef1 != null ?
                new ObjectParameter("docRef1", docRef1) :
                new ObjectParameter("docRef1", typeof(string));
    
            var docRef2Parameter = docRef2 != null ?
                new ObjectParameter("docRef2", docRef2) :
                new ObjectParameter("docRef2", typeof(string));
    
            var docRef3Parameter = docRef3 != null ?
                new ObjectParameter("docRef3", docRef3) :
                new ObjectParameter("docRef3", typeof(string));
    
            var docRef4Parameter = docRef4 != null ?
                new ObjectParameter("docRef4", docRef4) :
                new ObjectParameter("docRef4", typeof(string));
    
            var docRef5Parameter = docRef5 != null ?
                new ObjectParameter("docRef5", docRef5) :
                new ObjectParameter("docRef5", typeof(string));
    
            var fechaTransaccionParameter = fechaTransaccion.HasValue ?
                new ObjectParameter("fechaTransaccion", fechaTransaccion) :
                new ObjectParameter("fechaTransaccion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INSERCION_INVENTARIO", codCiaParameter, companiaVenta3Parameter, almacenVentaParameter, tipoMovimientoParameter, tipoDocumentoParameter, nroDocumentoParameter, codItem2Parameter, proveedorParameter, almacenDestinoParameter, cantidadParameter, docRef1Parameter, docRef2Parameter, docRef3Parameter, docRef4Parameter, docRef5Parameter, fechaTransaccionParameter);
        }
    }
}
