//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioDinet.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbModelEntities : DbContext
    {
        public DbModelEntities()
            : base("name=DbModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MOV_INVENTARIO> MOV_INVENTARIO { get; set; }
    
        public virtual int SP_ACTUALIZACION_INVENTARIO(string cOD_CIA, string cOMPANIA_VENTA_3, string aLMACEN_VENTA, string tIPO_MOVIMIENTO, string tIPO_DOCUMENTO, string nRO_DOCUMENTO, string cOD_ITEM_2, string pROVEEDOR, string aLMACEN_DESTINO, Nullable<int> cANTIDAD, string dOC_REF_1, string dOC_REF_2, string dOC_REF_3, string dOC_REF_4, string dOC_REF_5, Nullable<System.DateTime> fECHA_TRANSACCION)
        {
            var cOD_CIAParameter = cOD_CIA != null ?
                new ObjectParameter("COD_CIA", cOD_CIA) :
                new ObjectParameter("COD_CIA", typeof(string));
    
            var cOMPANIA_VENTA_3Parameter = cOMPANIA_VENTA_3 != null ?
                new ObjectParameter("COMPANIA_VENTA_3", cOMPANIA_VENTA_3) :
                new ObjectParameter("COMPANIA_VENTA_3", typeof(string));
    
            var aLMACEN_VENTAParameter = aLMACEN_VENTA != null ?
                new ObjectParameter("ALMACEN_VENTA", aLMACEN_VENTA) :
                new ObjectParameter("ALMACEN_VENTA", typeof(string));
    
            var tIPO_MOVIMIENTOParameter = tIPO_MOVIMIENTO != null ?
                new ObjectParameter("TIPO_MOVIMIENTO", tIPO_MOVIMIENTO) :
                new ObjectParameter("TIPO_MOVIMIENTO", typeof(string));
    
            var tIPO_DOCUMENTOParameter = tIPO_DOCUMENTO != null ?
                new ObjectParameter("TIPO_DOCUMENTO", tIPO_DOCUMENTO) :
                new ObjectParameter("TIPO_DOCUMENTO", typeof(string));
    
            var nRO_DOCUMENTOParameter = nRO_DOCUMENTO != null ?
                new ObjectParameter("NRO_DOCUMENTO", nRO_DOCUMENTO) :
                new ObjectParameter("NRO_DOCUMENTO", typeof(string));
    
            var cOD_ITEM_2Parameter = cOD_ITEM_2 != null ?
                new ObjectParameter("COD_ITEM_2", cOD_ITEM_2) :
                new ObjectParameter("COD_ITEM_2", typeof(string));
    
            var pROVEEDORParameter = pROVEEDOR != null ?
                new ObjectParameter("PROVEEDOR", pROVEEDOR) :
                new ObjectParameter("PROVEEDOR", typeof(string));
    
            var aLMACEN_DESTINOParameter = aLMACEN_DESTINO != null ?
                new ObjectParameter("ALMACEN_DESTINO", aLMACEN_DESTINO) :
                new ObjectParameter("ALMACEN_DESTINO", typeof(string));
    
            var cANTIDADParameter = cANTIDAD.HasValue ?
                new ObjectParameter("CANTIDAD", cANTIDAD) :
                new ObjectParameter("CANTIDAD", typeof(int));
    
            var dOC_REF_1Parameter = dOC_REF_1 != null ?
                new ObjectParameter("DOC_REF_1", dOC_REF_1) :
                new ObjectParameter("DOC_REF_1", typeof(string));
    
            var dOC_REF_2Parameter = dOC_REF_2 != null ?
                new ObjectParameter("DOC_REF_2", dOC_REF_2) :
                new ObjectParameter("DOC_REF_2", typeof(string));
    
            var dOC_REF_3Parameter = dOC_REF_3 != null ?
                new ObjectParameter("DOC_REF_3", dOC_REF_3) :
                new ObjectParameter("DOC_REF_3", typeof(string));
    
            var dOC_REF_4Parameter = dOC_REF_4 != null ?
                new ObjectParameter("DOC_REF_4", dOC_REF_4) :
                new ObjectParameter("DOC_REF_4", typeof(string));
    
            var dOC_REF_5Parameter = dOC_REF_5 != null ?
                new ObjectParameter("DOC_REF_5", dOC_REF_5) :
                new ObjectParameter("DOC_REF_5", typeof(string));
    
            var fECHA_TRANSACCIONParameter = fECHA_TRANSACCION.HasValue ?
                new ObjectParameter("FECHA_TRANSACCION", fECHA_TRANSACCION) :
                new ObjectParameter("FECHA_TRANSACCION", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ACTUALIZACION_INVENTARIO", cOD_CIAParameter, cOMPANIA_VENTA_3Parameter, aLMACEN_VENTAParameter, tIPO_MOVIMIENTOParameter, tIPO_DOCUMENTOParameter, nRO_DOCUMENTOParameter, cOD_ITEM_2Parameter, pROVEEDORParameter, aLMACEN_DESTINOParameter, cANTIDADParameter, dOC_REF_1Parameter, dOC_REF_2Parameter, dOC_REF_3Parameter, dOC_REF_4Parameter, dOC_REF_5Parameter, fECHA_TRANSACCIONParameter);
        }
    
        public virtual ObjectResult<SP_CONSULTA_INVENTARIO_Result> SP_CONSULTA_INVENTARIO(string cOD_CIA, string cOMPANIA_VENTA_3, string aLMACEN_VENTA, string tIPO_MOVIMIENTO, string tIPO_DOCUMENTO, string nRO_DOCUMENTO, string cOD_ITEM_2, string pROVEEDOR, string aLMACEN_DESTINO, Nullable<int> cANTIDAD, string dOC_REF_1, string dOC_REF_2, string dOC_REF_3, string dOC_REF_4, string dOC_REF_5, Nullable<System.DateTime> fECHA_TRANSACCION)
        {
            var cOD_CIAParameter = cOD_CIA != null ?
                new ObjectParameter("COD_CIA", cOD_CIA) :
                new ObjectParameter("COD_CIA", typeof(string));
    
            var cOMPANIA_VENTA_3Parameter = cOMPANIA_VENTA_3 != null ?
                new ObjectParameter("COMPANIA_VENTA_3", cOMPANIA_VENTA_3) :
                new ObjectParameter("COMPANIA_VENTA_3", typeof(string));
    
            var aLMACEN_VENTAParameter = aLMACEN_VENTA != null ?
                new ObjectParameter("ALMACEN_VENTA", aLMACEN_VENTA) :
                new ObjectParameter("ALMACEN_VENTA", typeof(string));
    
            var tIPO_MOVIMIENTOParameter = tIPO_MOVIMIENTO != null ?
                new ObjectParameter("TIPO_MOVIMIENTO", tIPO_MOVIMIENTO) :
                new ObjectParameter("TIPO_MOVIMIENTO", typeof(string));
    
            var tIPO_DOCUMENTOParameter = tIPO_DOCUMENTO != null ?
                new ObjectParameter("TIPO_DOCUMENTO", tIPO_DOCUMENTO) :
                new ObjectParameter("TIPO_DOCUMENTO", typeof(string));
    
            var nRO_DOCUMENTOParameter = nRO_DOCUMENTO != null ?
                new ObjectParameter("NRO_DOCUMENTO", nRO_DOCUMENTO) :
                new ObjectParameter("NRO_DOCUMENTO", typeof(string));
    
            var cOD_ITEM_2Parameter = cOD_ITEM_2 != null ?
                new ObjectParameter("COD_ITEM_2", cOD_ITEM_2) :
                new ObjectParameter("COD_ITEM_2", typeof(string));
    
            var pROVEEDORParameter = pROVEEDOR != null ?
                new ObjectParameter("PROVEEDOR", pROVEEDOR) :
                new ObjectParameter("PROVEEDOR", typeof(string));
    
            var aLMACEN_DESTINOParameter = aLMACEN_DESTINO != null ?
                new ObjectParameter("ALMACEN_DESTINO", aLMACEN_DESTINO) :
                new ObjectParameter("ALMACEN_DESTINO", typeof(string));
    
            var cANTIDADParameter = cANTIDAD.HasValue ?
                new ObjectParameter("CANTIDAD", cANTIDAD) :
                new ObjectParameter("CANTIDAD", typeof(int));
    
            var dOC_REF_1Parameter = dOC_REF_1 != null ?
                new ObjectParameter("DOC_REF_1", dOC_REF_1) :
                new ObjectParameter("DOC_REF_1", typeof(string));
    
            var dOC_REF_2Parameter = dOC_REF_2 != null ?
                new ObjectParameter("DOC_REF_2", dOC_REF_2) :
                new ObjectParameter("DOC_REF_2", typeof(string));
    
            var dOC_REF_3Parameter = dOC_REF_3 != null ?
                new ObjectParameter("DOC_REF_3", dOC_REF_3) :
                new ObjectParameter("DOC_REF_3", typeof(string));
    
            var dOC_REF_4Parameter = dOC_REF_4 != null ?
                new ObjectParameter("DOC_REF_4", dOC_REF_4) :
                new ObjectParameter("DOC_REF_4", typeof(string));
    
            var dOC_REF_5Parameter = dOC_REF_5 != null ?
                new ObjectParameter("DOC_REF_5", dOC_REF_5) :
                new ObjectParameter("DOC_REF_5", typeof(string));
    
            var fECHA_TRANSACCIONParameter = fECHA_TRANSACCION.HasValue ?
                new ObjectParameter("FECHA_TRANSACCION", fECHA_TRANSACCION) :
                new ObjectParameter("FECHA_TRANSACCION", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CONSULTA_INVENTARIO_Result>("SP_CONSULTA_INVENTARIO", cOD_CIAParameter, cOMPANIA_VENTA_3Parameter, aLMACEN_VENTAParameter, tIPO_MOVIMIENTOParameter, tIPO_DOCUMENTOParameter, nRO_DOCUMENTOParameter, cOD_ITEM_2Parameter, pROVEEDORParameter, aLMACEN_DESTINOParameter, cANTIDADParameter, dOC_REF_1Parameter, dOC_REF_2Parameter, dOC_REF_3Parameter, dOC_REF_4Parameter, dOC_REF_5Parameter, fECHA_TRANSACCIONParameter);
        }
    
        public virtual int SP_ELIMINACION_INVENTARIO(string cOD_CIA, string cOMPANIA_VENTA_3, string aLMACEN_VENTA, string tIPO_MOVIMIENTO, string tIPO_DOCUMENTO, string nRO_DOCUMENTO, string cOD_ITEM_2)
        {
            var cOD_CIAParameter = cOD_CIA != null ?
                new ObjectParameter("COD_CIA", cOD_CIA) :
                new ObjectParameter("COD_CIA", typeof(string));
    
            var cOMPANIA_VENTA_3Parameter = cOMPANIA_VENTA_3 != null ?
                new ObjectParameter("COMPANIA_VENTA_3", cOMPANIA_VENTA_3) :
                new ObjectParameter("COMPANIA_VENTA_3", typeof(string));
    
            var aLMACEN_VENTAParameter = aLMACEN_VENTA != null ?
                new ObjectParameter("ALMACEN_VENTA", aLMACEN_VENTA) :
                new ObjectParameter("ALMACEN_VENTA", typeof(string));
    
            var tIPO_MOVIMIENTOParameter = tIPO_MOVIMIENTO != null ?
                new ObjectParameter("TIPO_MOVIMIENTO", tIPO_MOVIMIENTO) :
                new ObjectParameter("TIPO_MOVIMIENTO", typeof(string));
    
            var tIPO_DOCUMENTOParameter = tIPO_DOCUMENTO != null ?
                new ObjectParameter("TIPO_DOCUMENTO", tIPO_DOCUMENTO) :
                new ObjectParameter("TIPO_DOCUMENTO", typeof(string));
    
            var nRO_DOCUMENTOParameter = nRO_DOCUMENTO != null ?
                new ObjectParameter("NRO_DOCUMENTO", nRO_DOCUMENTO) :
                new ObjectParameter("NRO_DOCUMENTO", typeof(string));
    
            var cOD_ITEM_2Parameter = cOD_ITEM_2 != null ?
                new ObjectParameter("COD_ITEM_2", cOD_ITEM_2) :
                new ObjectParameter("COD_ITEM_2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINACION_INVENTARIO", cOD_CIAParameter, cOMPANIA_VENTA_3Parameter, aLMACEN_VENTAParameter, tIPO_MOVIMIENTOParameter, tIPO_DOCUMENTOParameter, nRO_DOCUMENTOParameter, cOD_ITEM_2Parameter);
        }
    
        public virtual int SP_INSERCION_INVENTARIO(string cOD_CIA, string cOMPANIA_VENTA_3, string aLMACEN_VENTA, string tIPO_MOVIMIENTO, string tIPO_DOCUMENTO, string nRO_DOCUMENTO, string cOD_ITEM_2, string pROVEEDOR, string aLMACEN_DESTINO, Nullable<int> cANTIDAD, string dOC_REF_1, string dOC_REF_2, string dOC_REF_3, string dOC_REF_4, string dOC_REF_5, Nullable<System.DateTime> fECHA_TRANSACCION)
        {
            var cOD_CIAParameter = cOD_CIA != null ?
                new ObjectParameter("COD_CIA", cOD_CIA) :
                new ObjectParameter("COD_CIA", typeof(string));
    
            var cOMPANIA_VENTA_3Parameter = cOMPANIA_VENTA_3 != null ?
                new ObjectParameter("COMPANIA_VENTA_3", cOMPANIA_VENTA_3) :
                new ObjectParameter("COMPANIA_VENTA_3", typeof(string));
    
            var aLMACEN_VENTAParameter = aLMACEN_VENTA != null ?
                new ObjectParameter("ALMACEN_VENTA", aLMACEN_VENTA) :
                new ObjectParameter("ALMACEN_VENTA", typeof(string));
    
            var tIPO_MOVIMIENTOParameter = tIPO_MOVIMIENTO != null ?
                new ObjectParameter("TIPO_MOVIMIENTO", tIPO_MOVIMIENTO) :
                new ObjectParameter("TIPO_MOVIMIENTO", typeof(string));
    
            var tIPO_DOCUMENTOParameter = tIPO_DOCUMENTO != null ?
                new ObjectParameter("TIPO_DOCUMENTO", tIPO_DOCUMENTO) :
                new ObjectParameter("TIPO_DOCUMENTO", typeof(string));
    
            var nRO_DOCUMENTOParameter = nRO_DOCUMENTO != null ?
                new ObjectParameter("NRO_DOCUMENTO", nRO_DOCUMENTO) :
                new ObjectParameter("NRO_DOCUMENTO", typeof(string));
    
            var cOD_ITEM_2Parameter = cOD_ITEM_2 != null ?
                new ObjectParameter("COD_ITEM_2", cOD_ITEM_2) :
                new ObjectParameter("COD_ITEM_2", typeof(string));
    
            var pROVEEDORParameter = pROVEEDOR != null ?
                new ObjectParameter("PROVEEDOR", pROVEEDOR) :
                new ObjectParameter("PROVEEDOR", typeof(string));
    
            var aLMACEN_DESTINOParameter = aLMACEN_DESTINO != null ?
                new ObjectParameter("ALMACEN_DESTINO", aLMACEN_DESTINO) :
                new ObjectParameter("ALMACEN_DESTINO", typeof(string));
    
            var cANTIDADParameter = cANTIDAD.HasValue ?
                new ObjectParameter("CANTIDAD", cANTIDAD) :
                new ObjectParameter("CANTIDAD", typeof(int));
    
            var dOC_REF_1Parameter = dOC_REF_1 != null ?
                new ObjectParameter("DOC_REF_1", dOC_REF_1) :
                new ObjectParameter("DOC_REF_1", typeof(string));
    
            var dOC_REF_2Parameter = dOC_REF_2 != null ?
                new ObjectParameter("DOC_REF_2", dOC_REF_2) :
                new ObjectParameter("DOC_REF_2", typeof(string));
    
            var dOC_REF_3Parameter = dOC_REF_3 != null ?
                new ObjectParameter("DOC_REF_3", dOC_REF_3) :
                new ObjectParameter("DOC_REF_3", typeof(string));
    
            var dOC_REF_4Parameter = dOC_REF_4 != null ?
                new ObjectParameter("DOC_REF_4", dOC_REF_4) :
                new ObjectParameter("DOC_REF_4", typeof(string));
    
            var dOC_REF_5Parameter = dOC_REF_5 != null ?
                new ObjectParameter("DOC_REF_5", dOC_REF_5) :
                new ObjectParameter("DOC_REF_5", typeof(string));
    
            var fECHA_TRANSACCIONParameter = fECHA_TRANSACCION.HasValue ?
                new ObjectParameter("FECHA_TRANSACCION", fECHA_TRANSACCION) :
                new ObjectParameter("FECHA_TRANSACCION", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INSERCION_INVENTARIO", cOD_CIAParameter, cOMPANIA_VENTA_3Parameter, aLMACEN_VENTAParameter, tIPO_MOVIMIENTOParameter, tIPO_DOCUMENTOParameter, nRO_DOCUMENTOParameter, cOD_ITEM_2Parameter, pROVEEDORParameter, aLMACEN_DESTINOParameter, cANTIDADParameter, dOC_REF_1Parameter, dOC_REF_2Parameter, dOC_REF_3Parameter, dOC_REF_4Parameter, dOC_REF_5Parameter, fECHA_TRANSACCIONParameter);
        }
    }
}
