//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioDinet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOV_INVENTARIO
    {
        public string COD_CIA { get; set; }
        public string COMPANIA_VENTA_3 { get; set; }
        public string ALMACEN_VENTA { get; set; }
        public string TIPO_MOVIMIENTO { get; set; }
        public string TIPO_DOCUMENTO { get; set; }
        public string NRO_DOCUMENTO { get; set; }
        public string COD_ITEM_2 { get; set; }
        public string PROVEEDOR { get; set; }
        public string ALMACEN_DESTINO { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public string DOC_REF_1 { get; set; }
        public string DOC_REF_2 { get; set; }
        public string DOC_REF_3 { get; set; }
        public string DOC_REF_4 { get; set; }
        public string DOC_REF_5 { get; set; }
        public Nullable<System.DateTime> FECHA_TRANSACCION { get; set; }
    }
}
